queue_rules:
  - name: default
    conditions:
      - "status-success=Travis CI - Pull Request"

pull_request_rules:
  - name: Automatic merge passing PR on up to date branch with approving CR
    conditions:
      - "base=develop"
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "status-success=Travis CI - Pull Request"
      - "label!=work-in-progress"
    actions:
      queue:
        name: default

  - name: Request Brian to review changes to the core API
    conditions:
      - "-files~=^can/interfaces/$"
      - "-closed"
      - "author!=hardbyte"
    actions:
      request_reviews:
        users:
          - hardbyte

  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
