def doIPythonImports(ip_engine):
    ip_engine.ex("print 'Importing ipipe library...'")
    ip_engine.ex("from ipipe import *")
    ip_engine.ex("print 'Importing pycanlib IPython extensions...'")
    ip_engine.ex("print '\tReadCAN...'")
    ip_engine.ex("from pycanlib.ipython.ReadCAN import *")
    ip_engine.ex("print '\tWriteCAN...'")
    ip_engine.ex("from pycanlib.ipython.WriteCAN import *")
    ip_engine.ex("print '\tPrintCAN...'")
    ip_engine.ex("from pycanlib.ipython.PrintCAN import *")
#    ip_engine.ex("print '\tReadLog...'")
#    ip_engine.ex("from pycanlib.ipython.ReadLog import *")
#    ip_engine.ex("print '\tWriteLog...'")
#    ip_engine.ex("from pycanlib.ipython.WriteLog import *")
    ip_engine.ex("print '\tAcceptanceFilter...'")
    ip_engine.ex("from pycanlib.ipython.AcceptanceFilter import *")
    ip_engine.ex("print '\tExtractTimeslice...'")
    ip_engine.ex("from pycanlib.ipython.ExtractTimeslice import *")
