def doIPythonImports(ip_engine):
    ip_engine.ex("print 'Importing ipipe library...'")
    ip_engine.ex("from ipipe import *")
    ip_engine.ex("print 'Importing pycanlib IPython extensions...'")
    ip_engine.ex("print '\tReadCAN...'")
    ip_engine.ex("from pycanlib.ipython.ReadCAN import *")
    ip_engine.ex("print '\tWriteCAN...'")
    ip_engine.ex("from pycanlib.ipython.WriteCAN import *")
    ip_engine.ex("print '\tPrintCAN...'")
    ip_engine.ex("from pycanlib.ipython.PrintCAN import *")
    ip_engine.ex("print '\tLogCAN...'")
    ip_engine.ex("from pycanlib.ipython.LogCAN import *")
#    ip_engine.ex("print '\tReadCANLog...'")
#    ip_engine.ex("from pycanlib.ipython.ReadCANLog import *")
#    ip_engine.ex("print '\tReadSSTLog...'")
#    ip_engine.ex("from pycanlib.ipython.ReadSSTLog import *")
#    ip_engine.ex("print '\tFilterDevices...'")
#    ip_engine.ex("from pycanlib.ipython.FilterDevices import *")
#    ip_engine.ex("print '\tExtractTimeslice...'")
#    ip_engine.ex("from pycanlib.ipython.ExtractTimeslice import *")
